# Generated by Django 6.1 on 2026-08-30 16:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritagerecord',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/qr_codes/', location='/home/rakshi/heritagehub-backend1/media/qr_codes'), upload_to=''),
        ),
    ]
