# Generated by Django 6.1 on 2026-08-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedgeneration',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='3d/models/'),
        ),
    ]
