# Generated by Django 6.1 on 2026-08-31 19:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threed', '0002_threedgeneration_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedgeneration',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='threed/input_images/'),
        ),
    ]
