# Generated by Django 6.1 on 2026-08-31 19:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threed', '0003_alter_threedgeneration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedgeneration',
            name='model_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='3d/models/'),
        ),
    ]
