"""
Django settings for heritagehub project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url


# ==================================================
# LOAD ENVIRONMENT VARIABLES
# ==================================================

load_dotenv()


# ==================================================
# BASE DIRECTORY
# ==================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ==================================================
# SECURITY
# ==================================================

SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "heritagehub-backend1.onrender.com,127.0.0.1,localhost"
).split(",")


# ==================================================
# AI CONFIGURATION
# ==================================================

AI_API_KEY = os.getenv("AI_API_KEY")

AI_MODEL_NAME = os.getenv(
    "AI_MODEL_NAME",
    "gemini-3.5-flash-lite"
)

MESHY_API_KEY = os.getenv("MESHY_API_KEY")


# ==================================================
# APPLICATIONS
# ==================================================

INSTALLED_APPS = [

    # ------------------------------
    # Django
    # ------------------------------

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # ------------------------------
    # Third-party
    # ------------------------------

    "rest_framework",
    "corsheaders",

    "cloudinary_storage",
    "cloudinary",

    # ------------------------------
    # HeritageHub apps
    # ------------------------------

    "accounts",
    "heritage",
    "community",
    "ai_assistant",
    "dashboard",
    "shopping",
    "explore",
    "learn",
    "threed",
    "canvas",
]


# ==================================================
# MIDDLEWARE
# ==================================================

MIDDLEWARE = [

    # IMPORTANT:
    # CORS middleware must be near the top.
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ==================================================
# URL CONFIGURATION
# ==================================================

ROOT_URLCONF = "heritagehub.urls"


# ==================================================
# TEMPLATES
# ==================================================

TEMPLATES = [

    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],
        },
    },
]


# ==================================================
# WSGI
# ==================================================

WSGI_APPLICATION = "heritagehub.wsgi.application"


# ==================================================
# DATABASE
# ==================================================

DATABASES = {

    "default": dj_database_url.config(

        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",

        conn_max_age=600,

    )

}


# ==================================================
# PASSWORD VALIDATION
# ==================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]


# ==================================================
# INTERNATIONALIZATION
# ==================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ==================================================
# CUSTOM USER MODEL
# ==================================================

AUTH_USER_MODEL = "accounts.User"


# ==================================================
# STATIC FILES
# ==================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# ==================================================
# CLOUDINARY
# ==================================================

CLOUDINARY_STORAGE = {

    "CLOUD_NAME": os.getenv(
        "CLOUDINARY_CLOUD_NAME"
    ),

    "API_KEY": os.getenv(
        "CLOUDINARY_API_KEY"
    ),

    "API_SECRET": os.getenv(
        "CLOUDINARY_API_SECRET"
    ),

    "RESOURCE_TYPE": "auto",

}


# ==================================================
# STORAGE
# ==================================================

STORAGES = {

    "default": {

        "BACKEND":
        "cloudinary_storage.storage.MediaCloudinaryStorage",

    },

    "staticfiles": {

        "BACKEND":
        "whitenoise.storage.CompressedManifestStaticFilesStorage",

    },

}


# ==================================================
# MEDIA
# ==================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ==================================================
# CORS CONFIGURATION
# ==================================================

# Production frontend
CORS_ALLOWED_ORIGINS = [

    "https://heritagehub-frontend1.vercel.app",

    # Local development
    "http://localhost:5173",

    "http://localhost:3000",

]


# Allow cookies/authentication across origins
CORS_ALLOW_CREDENTIALS = True


# HTTP methods allowed by the frontend
CORS_ALLOW_METHODS = [

    "DELETE",

    "GET",

    "OPTIONS",

    "PATCH",

    "POST",

    "PUT",

]


# Headers allowed from the frontend
CORS_ALLOW_HEADERS = [

    "accept",

    "accept-encoding",

    "authorization",

    "content-type",

    "dnt",

    "origin",

    "user-agent",

    "x-csrftoken",

    "x-requested-with",

]


# ==================================================
# CSRF
# ==================================================

CSRF_TRUSTED_ORIGINS = [

    "https://heritagehub-frontend1.vercel.app",

    "http://localhost:5173",

    "http://localhost:3000",

]


# ==================================================
# DJANGO REST FRAMEWORK
# ==================================================

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (

        "rest_framework_simplejwt.authentication.JWTAuthentication",

    ),

}


# ==================================================
# EMAIL
# ==================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)


# ==================================================
# DEFAULT PRIMARY KEY
# ==================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"