# Generated by Django 6.1 on 2026-08-20 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorePlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='explore/main/')),
                ('culture_title', models.CharField(blank=True, max_length=200)),
                ('culture_description', models.TextField(blank=True)),
                ('culture_image', models.ImageField(blank=True, null=True, upload_to='explore/culture/')),
                ('food_title', models.CharField(blank=True, max_length=200)),
                ('food_description', models.TextField(blank=True)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='explore/food/')),
                ('story_audio', models.FileField(blank=True, null=True, upload_to='explore/audio/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ExploreEra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='explore/eras/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eras', to='explore.exploreplace')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
