# Generated by Django 6.1 on 2026-08-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DancePose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_name', models.CharField(default='Odissi', max_length=100)),
                ('pose_name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='learn_dance/')),
                ('explanation', models.TextField(blank=True)),
                ('tutorial_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LanguagePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('greetings', 'Greetings'), ('everyday', 'Everyday Words'), ('family', 'Family'), ('food', 'Food'), ('travel', 'Travel'), ('culture', 'Culture'), ('numbers', 'Numbers'), ('sentences', 'Common Sentences')], max_length=20)),
                ('english_phrase', models.CharField(max_length=300)),
                ('odia_translation', models.CharField(max_length=300)),
                ('audio', models.FileField(blank=True, null=True, upload_to='learn_language/')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='learn_langu_categor_dd226c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('audio', models.FileField(blank=True, null=True, upload_to='learn_songs/')),
                ('lyrics', models.TextField(blank=True)),
                ('cultural_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='learn_song_title_f68bce_idx')],
            },
        ),
    ]
