# Generated by Django 6.1 on 2026-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_song_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('sambalpuri', 'Sambalpuri'), ('koraputia', 'Koraputia'), ('bhajan', 'Odia Bhajan'), ('santali', 'Santali')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='learn_songs_images/'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='learn_song_genre_72da15_idx'),
        ),
    ]
