# Generated by Django 6.1 on 2026-08-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_song_artist_song_genre_song_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancepose',
            name='dance_name',
            field=models.CharField(choices=[('odissi', 'Odissi'), ('dhemsa', 'Dhemsa'), ('sambalpuri', 'Sambalpuri')], default='odissi', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dancepose',
            index=models.Index(fields=['dance_name'], name='learn_dance_dance_n_c26e25_idx'),
        ),
    ]
