# Generated by Django 6.1 on 2026-08-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_alter_dancepose_dance_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RitualPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('cultural_significance', models.TextField(blank=True)),
                ('practices', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='learn_rituals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='learn_ritua_title_41db84_idx'), models.Index(fields=['region'], name='learn_ritua_region_1acb44_idx')],
            },
        ),
    ]
