# Generated by Django 6.1 on 2026-08-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_ritualpractice'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cloudinary_audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
